### ISSUE TITLE
Modify the II to First Improvement

### ISSUE THREAD

**Issue by CorcovadoMing** [CorcovadoMing/MemeticAlgorithm#1]
For speed up the experiment

**Comment by BazukaOC** [comment]
finished the modify. Should I close the issue?

**Comment by CorcovadoMing** [comment]
May I ask why include the limits header ?

**Comment by BazukaOC** [comment]
INT_MAX will crush without limits header.
is that normal??
I use Code Blocks.

**Comment by CorcovadoMing** [comment]
What "crash" do you mean? can't compile? runtime crash?
Do you add the flag "std=c++11" when compile?

**Comment by BazukaOC** [comment]
Can't build it. error msg return. Yes, I added. I'm really sure.
here's the text:
\MemeticAlgorithm.cpp|183|error: 'INT_MAX' was not declared in this scope

**Comment by CorcovadoMing** [comment]
OK, maybe I should check about it
Anyway, we are out of the topic, this issue will close
